#!/usr/bin/env bash
#
# Install packages, run all installers and symlink dotfiles.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo "Bootstrapping"

# First of all install homebrew
$DOTFILES_ROOT/homebrew/install.sh 2>&1
ln -sf $DOTFILES_ROOT/homebrew/Brewfile ~/.Brewfile
brew update

script/pkg
script/install
script/symlinks
