#!/usr/bin/env bash
#
# Run all installers and symlink dotfiles

set -e

echo "Bootstrapping"

# Install homebrew
$ZSH/homebrew/install.sh 2>&1

brew update

brew bundle --file=$ZSH/homebrew/Brewfile

script/install
script/symlinks
