#!/usr/bin/env bash
#
# Run all installers and symlink dotfiles

set -e

Echo "Bootstrapping"

script/install
script/symlinks

# Install packages from Brewfile
brew bundle

# TODO: at some point m is supposed to be available via brew
# See https://github.com/rgcr/m-cli
curl -fsSL https://raw.githubusercontent.com/rgcr/m-cli/master/install.sh | sh
